### ISSUE TITLE
'MacOS install' page issue

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/website#2460]
Page URL: https://flutter.dev/docs/get-started/install/macos.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/macos.md

Since the move to using flutter.dev (I think) it now does not work on our firewall. can both sites remain intact as mirrors rather than redirecting, or somehow otherwise have this be fixed on flutter's side?

Or can i get something more specific that doesnt cause our IT dept to go "huh?: if i try to report it... Preferably a fix on Flutter's end. (see the blue Loading...) button

Description of issue:
![image](https://user-images.githubusercontent.com/3019617/53655716-921f9080-3c16-11e9-9e12-7995b4fccd0d.png)

**Comment by filiph** [comment]
cc @kf6gpe for visibility.

**Comment by kf6gpe** [comment]
I’d be curious to know how widespread this problem is, if others could comment. Also, how likely is it that firewalls are just confused by .dev in general? A long term fix would be to modify our publishing so we publish to both sites and take away the forwarding. If this turns out to be a long term problem for folks, I’m certainly open to that, although it kind of defeats the notion of launching the .dev domain overall. @mit-mit and @timsneath and I should discuss more next week, with input of course from @Sfshaza. Thanks for reporting it!!

**Comment by timsneath** [comment]
I suspect our script needs to be more resilient to failure; perhaps some kind of timeout, or the script should be server-side? And of course, we always have the [direct links to the SDK archive](https://flutter.dev/docs/development/tools/sdk/archive) -- perhaps they should be described not merely as being 'for other release channels, and older builds'...

In the short term, I'd love to understand where it's failing -- @neiljaywarner is there any way to identify where it's blocked?

Unfortunately, I don't think we can take responsibility for firewalls that block legitimate parts of the internet by mirroring content elsewhere. That seems like a never-ending slippery slope.

**Comment by neiljaywarner** [comment]
@timsneath I'm not sure how to find out where it is failing (a look at the html source and chrome devtools did not yield anything useful from my perspective.. didn't try charles or anything) but... I am pretty sure This issue will be resolved by the scripts being server side, which would be appreciated - especially if the same script would then affect the code block so that the file to unzip was described with the exact name from the download link instead of x.x.y - just a small bonus for people.

Plus more to the point it looks broken with the "Loading..." - and, unfortunately, the SDK archives page also does not work! (similarly gives loading...)

**Comment by neiljaywarner** [comment]
@timsneath Perhaps you can  please try to have one of the web devs identify in base.js or similar what server is being utilized and i can ask IT to whitelist it? (I think my boss will approve it promptly)

**Comment by sfshaza2** [comment]
OK, we *think* we've fixed this. flutter.io is now serving out of the same firebase project as flutter.dev. There are several other bugs filed against this issue, but with less info. I'm closing those out.

Please let us know if you continue to experience this problem!

**Comment by neiljaywarner** [comment]
@sfshaza2 thanks so much for working onthis.
i still get the same "loading..." blue button.

although... firefox and safari both work as expected... even though chrome previously worked properly, for flutter 1.0 and flutter.io ...  Is that weird?

**Comment by sfshaza2** [comment]
Thanks for checking, @neiljaywarner!

**Comment by kf6gpe** [comment]
@neiljaywarner thanks for continuing to look at this with us! Can you try this and grab a snapshot of your JavaScript console? That should be (on Chrome, anyway) the options->More Tools->Developer Tools->Console? We're wondering if there's a JavaScript error that will give us a clue. Thanks!!

cc @filiph too, who's working on this with me.

**Comment by filiph** [comment]
JS console log would be super helpful.

FWIW, I think the solution will be somewhere around https://github.com/flutter/website/blob/master/src/_assets/js/archive.js#L7. There's nothing wrong with the function, afaik, but it looks like:

* Other JavaScript works for @neiljaywarner (I assume)
* Only the ajax call fails.
* This wasn't an issue before we moved to the .dev TLD

This points to something that only affects JS http requests, and only to .dev domains (or, more generally, to new TLDs). Weird, but possible.

**Comment by neiljaywarner** [comment]
@filiph  @kf6gpe  thanks
Well, for further info .. https://storage.googleapis.com/flutter_infra/releases/releases_macos.json *does* work without any problem directly in the browser (as you said, just the ajax).. . .i tried looking at the network requests and saw something useful. can you please point me to instructions on how to view the console log if you have time. thanks

**Comment by filiph** [comment]
@neiljaywarner I made this short gif:

![js-console](https://user-images.githubusercontent.com/919717/53994548-72410e80-40e7-11e9-9d20-6a97d1435f81.gif)

It's showing: 

1) go to the https://flutter.dev/docs/get-started/install/ page for your platform 
2) open the developer tools, 
3) make sure you're on the "Console" tab, 
4) re-fresh the site.

**Comment by neiljaywarner** [comment]
@filiph  that is very kind of you to be so thorough.  The part you show in your gif is exactly the  part I did see, but when i refresh the site there is no output to the console - similar to how your shows nothing in the red circle area in the console at the end of the gif.

**Comment by neiljaywarner** [comment]
if it helps for diagnostic purposes, i go to a semi-random dev site https://developer.android.com/guide/topics/permissions/overview and use your procedure in the gif and the console says the below. of course, i'm not suggesting you troubleshoot that site, i'm just giving more info.

thank you.



Access to fetch at 'https://www.gstatic.com/images/icons/material/product/2x/youtube_48dp.png' from origin 'https://developer.android.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by filiph** [comment]
Hmm, that's already helpful information! So, there's no error.

What happens in the Network tab (two tabs right from Console)?

**Comment by neiljaywarner** [comment]
nothing useful afaik :(
i checked that first...
![image](https://user-images.githubusercontent.com/3019617/53996177-14b7bc80-40fd-11e9-9eda-9a7b09733484.png)

--
macos	304	document	Other	901 B	9 ms	flutter-lockup-4cb0ee072ab312e59784d9fbf4fb7ad42688a7fdaea1270ccf6bbf4f34b7e03f.svg	200	svg+xml	macos	(from memory cache)	0 ms	xcode-account.png	200	png	macos	(from memory cache)	0 ms	trust-computer.png	200	png	macos	(from memory cache)	0 ms	xcode-unique-bundle-id.png	200	png	macos	(from memory cache)	0 ms	flutter-mono-81x100.png	200	png	macos	(from memory cache)	0 ms	css?family=Google+Sans:400,500|Roboto:300,400,500|Roboto+Mono:400,700|Material+Icons	200	stylesheet	macos	(from disk cache)	1 ms	main-210cacaf48055341d9f0d3a85317cce241a3588a283b2709e265ebc2fdba2a23.css	200	stylesheet	macos	(from disk cache)	3 ms	4UaGrENHsxJlGDuGo1OIlL3Owp5eKQtG.woff2	200	font	Other	(from memory cache)	0 ms	4UabrENHsxJlGDuGo1OIlLU94YtzCwZsPF4o.woff2	200	font	Other	(from memory cache)	0 ms	flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2	200	font	Other	(from memory cache)	0 ms	KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2	200	font	Other	(from memory cache)	0 ms	KFOlCnqEu92Fr1MmEU9fBBc4AMP6lQ.woff2	200	font	Other	(from memory cache)	0 ms	L0x5DF4xlVMF-BfR8bXMIjhLq3-cXbKD.woff2	200	font	Other	(from memory cache)	0 ms	L0xkDF4xlVMF-BfR8bXMIjDwjmqxf7-pAVU_.woff2	200	font	Other	(from memory cache)	0 ms	fa-solid-900-7798165ee5a3c6809310d8261dcbe7c8d0c12d795b7b09a71af3eb86ec8f33f2.woff2	200	font	Other	(from memory cache)	0 ms	fa-brands-400-05dbc51654b96590d176c27efbcef2cf4ac0497499a9f28b731b73eea399070c.woff2	200	font	Other	(from memory cache)	0 ms	flutter-chevron-bg.svg	200	svg+xml	Other	(from memory cache)	0 ms	favicon.png	200	png	Other	1.4 KB	8 ms	
--

**Comment by filiph** [comment]
Weird. 

Does other JavaScript on the site work? For example, can you open and close carets in the left navigation bar?

Can you make another screenshot of the Network tab, but this time, just before the screenshot, hit Cmd-Shift-R (force reload)? This should make sure that every network request is tried again.

**Comment by neiljaywarner** [comment]
@filiph the carets also do not open and close; sorry i forgot to point that out.

**Comment by cneilmon** [comment]
hey! look at the comment here: https://github.com/flutter/website/issues/2595
seems its already working fine
