### ISSUE TITLE
Update FAQ on x86

### ISSUE THREAD

**Issue by mit-mit** [flutter/website#4039]
From https://flutter.dev/docs/resources/faq#what-devices-and-os-versions-does-flutter-run-on:

> Note Flutter currently does not support building for x86 Android (issue #9253) directly, however apps built for ARMv7 or ARM64 run fine (via ARM emulation) on many x86 Android devices.

However, https://github.com/flutter/flutter/issues/9253 is resolved, so this likely needs an update

**Comment by sfshaza2** [comment]
Fixed.

**Comment by kw2019ltd** [comment]
still not supported
flutter build apk --target-platform android-x86 is failing

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileReleaseJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
   > Could not find io.flutter:x86_release:1.0.0-540786dd51f112885a89792d678296b95e6622e5.
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 5s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      66.6s
Gradle task assembleRelease failed with exit code 1
