### ISSUE TITLE
Syntax Error in the docs void _pushSaved()

### ISSUE THREAD

**Issue by pinguin999** [flutter/website#5270]
At https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2#5
In this Code block

``` Dart
  void _pushSaved() {
    Navigator.of(context).push(
      MaterialPageRoute<void>(
        // NEW lines from here...
        builder: (BuildContext context) {
          final tiles = _saved.map(
            (WordPair pair) {
              return ListTile(
                title: Text(
                  pair.asPascalCase,
                  style: _biggerFont,
                ),
              );
            },
          );
          final divided = ListTile.divideTiles(
            context: context,
            tiles: tiles,
          ).toList();

          return Scaffold(
            appBar: AppBar(
              title: Text('Saved Suggestions'),
            ),
            body: ListView(children: divided),
          );
        }, // ...to here.
      ),
    );
  }
}
```

The last } is too much and than all code can be outdent by one tab.

And also the Link to report Issues is wrong: https://github.com/flutter/flutter/issues/75702

**Comment by sfshaza2** [comment]
@miquelbeltran, is this still an issue? If not, I'd like to close it. And, in fact, yes, he's right. Codelab issues should come to the flutter/website repo, not flutter/flutter.

**Comment by miquelbeltran** [comment]
Yes, looks like the extra curly bracket is present in the original document.

I fixed it on the copy of the doc I have.

**Comment by pinguin999** [comment]
@sfshaza2 yes it's still an issue. 
@miquelbeltran where is your copy of the docs?

**Comment by sfshaza2** [comment]
@pinguin999, Miquel was migrating our codelabs to null safety and that's where he fixed the issue. We made those live on 3/3 for the Flutter 2 launch. It is fixed now. Closing.
