### ISSUE TITLE
Update install dependency for Ubuntu 22.04 for 'Desktop support for Flutter': Linux "additional requirements" section

### ISSUE THREAD

**Issue by maks** [flutter/website#8016]
### Page URL

https://docs.flutter.dev/development/platform-integration/desktop#additional-linux-requirements

### Page source

https://github.com/flutter/website/tree/main/src/development/platform-integration/desktop.md#additional-linux-requirements

### Describe the problem

Currently the section has this text:
```
Run the following command

sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
```
This is now missing `libstdc++-12-dev` as was covered in  https://github.com/flutter/flutter/issues/115909#issuecomment-1330332515

I tested this on `Ubuntu 22.04.1` which the current LTS release and got the same error is in [this comment](https://github.com/flutter/flutter/issues/115909#issuecomment-1324774449) when trying to run a app created with `flutter create test_linux` installing `libstdc++-12-dev` with `apt`, running `flutter clean` again and then running allowed the counter app to run as expected.

### Expected fix

Change line to read:
```
sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
```

**Comment by parlough** [comment]
@cbracken Wasn't sure who to reach out to, but do you know if adding `libstdc++-12-dev` to the list of packages for Linux desktop support is the correct solution here? Is there a good way we can stay up to date with the requirements?

**Comment by maks** [comment]
@parlough as I understood it, the added dependency on the `libstdc++-12-dev` came about because that version of the  c++ std lib package was no longer an implicit transient dependency of one of the other listed dependencies. I suspect this wouldn't happen very often in the future but I guess the best way to spot this in the future would be CI machines failing because they don't have the required dependency?

**Comment by parlough** [comment]
Thanks for the extra context @maks, makes sense!

**Comment by kriswuollett** [comment]
Just encountered this as well. At least regarding addressing the issue in the website docs, I'd like to suggest adding a tabbed example code box that can accommodate a few of the most widely used Linux distributions to show the command line(s) to make sure the packages are installed, e.g., [the tabbed-format used in Google Cloud docs](https://cloud.google.com/sql/docs/postgres/sql-proxy?hl=en#install) which has a cool dropdown for tabs overflow.

**Comment by fertrig** [comment]
This change went in on early April. However, I don't see the change on the live website yet.

How often are the website changes published?

**Comment by leadVisionary** [comment]
Literally setup a new Linux Mint VM today with the whole Flutter/Android Studio stack and still ran into the [bug](https://github.com/flutter/flutter/issues/115909) after perusing [StackOverflow ](https://stackoverflow.com/questions/74543715/usr-bin-ld-cannot-find-lstdc-no-such-file-or-directory-on-running-flutte).

What is the ETA for having Flutter work out of the box on Ubuntu derivative distros?

**Comment by gnprice** [comment]
> This change went in on early April. However, I don't see the change on the live website yet.

I just opened the page and thought the same thing. But it looks like in fact the change is live — it's just that there are two lists of dependencies.

Specifically this dependency is now listed in the `apt-get install` command, but not in the text:
![image](https://github.com/flutter/website/assets/28173/bc5b4345-5fd4-45c5-a30a-f222d7b4b6c5)
(Note the bottom right at the end of the command, but the bulleted list ending with liblzma-dev.)

It'd be good to add it in the text too. Reopening this issue in hopes that's the easiest way to track it.

**Comment by fertrig** [comment]
@gnprice, I see what you are seeing on the [Desktop Support for Flutter](https://docs.flutter.dev/platform-integration/desktop#additional-linux-requirements) page. However, the [Linux Install](https://docs.flutter.dev/get-started/install/linux#linux-setup) page doesn't list the dependency.

I was expecting to see that dependency on this section: 

https://docs.flutter.dev/get-started/install/linux#additional-linux-requirements

That section doesn't list the `libstdc++-12-dev` dependency at all.

**Comment by gnprice** [comment]
> I was expecting to see that dependency on this section:
> 
> https://docs.flutter.dev/get-started/install/linux#additional-linux-requirements

Aha, I see. So there's another two copies of the list there (one in text and one in a command line), which should also be updated.

(Or perhaps it'd be helpful to make both those sections come from a single copy in the source tree, to make it easier to keep them in sync in the future. But I don't know enough about how the website works to know if there's a convenient way to do that.)

**Comment by cbracken** [comment]
Also not super familiar with whether there's a way to extract a single piece of text and inject it into multiple places in the website. @sfshaza2 is that something we can do? If not, I can send a patch for the above locations.

**Comment by sfshaza2** [comment]
@cbracken @gnprice, yes this is very possible! You can create the text as an include. The include can be local (say if multiple files in the same directory used the text), or it can be global. To see the global include files, check out the /src/_includes/docs directory in the repo.

To include it in the markdown file, use:

```
{% include docs/<file>.md %}
```

If you create the include file locally, prefix the file name with an underscore. Include that text as follows:

```
{% include_relative _<file>.md %}
```

**Comment by sfshaza2** [comment]
BTW, I also like the tabbed content idea. We can do that, too.  For example, see: https://docs.flutter.dev/get-started/editor?tab=vscode

**Comment by parlough** [comment]
Thanks everyone for the discussion! Fixed by https://github.com/flutter/website/commit/91e4cd59df610f0e0c06c3a3bd265951b68515e3 which uses includes to share the updated information.

**Comment by gnprice** [comment]
Great, that causes both pages to have the updated command.

The bulleted list in the text is still missing the new dependency `libstdc++-12-dev`, though:
![image](https://github.com/flutter/website/assets/28173/80d9ef05-360a-4094-830a-b2780c54594a)
so I think this isn't yet entirely fixed.

(It'd probably also be a good idea to add some sort of comment in each of those files `linux-requirements-command.md` and `liinux-requirements-list.md` mentioning it should be kept in sync with the other file. Otherwise it'd be very easy for the next update to happen on only one or the other, too.)
